### ISSUE TITLE
Shopware 5.4.0 compatibility

### ISSUE THREAD

**Issue by mgoeben** [hitmeister/shopware-plugin#12]
Hi!

Is there any chance that Shopware 5,4.0 compatibility is added soon?

Regards

Marco

**Comment by aazon** [comment]
Hi Marco,

We are working on the compatibility with version 5.4 but it is not scheduled for the soonest release.

Best Regards,
Alex

**Comment by mgoeben** [comment]
Hi!

I would like to ask again, because the new Shopware version exist now over one month.

Thank you in advance.

Gruß

Marco Göbenich

**Comment by aazon** [comment]
Hi Marco,

Thanks for your question.

We expect our plugin to support version 5.4 by the end of June. Currently, it is under active development.

Best Regards,
Alex

**Comment by mgoeben** [comment]
Hi!

Shopware 5.5 is already beta.
Is there any hint how to fix the plugin for 5.4
Regards

Marco

**Comment by aazon** [comment]
Hi Marco,

We released a [new version of the plugin](https://store.shopware.com/detail/index/sArticle/164974?number=webcu25585348743m). It supports Shopware 5.4 already.
The former plugin (which is in this repo) is deprecated and will not be supported anymore.

Best Regards,
Alex.
