### ISSUE TITLE
Produces Error LEGACY URL

### ISSUE THREAD

**Issue by JenSommer** [hitmeister/shopware-plugin#5]
Running on Shopware 5.2.21 (and 5.2.20) there are many many error like this while trying to fetch the IMG from their origin:

Legacy media url detected.
{
  "requestedUrl": "/media/image/thumbnail/IMAGE_200x200.jpg",
  "redirectedTo": "https://www.XXXs.de/media/image/c3/b6/d5/IMAGE_200x200.jpg"
}

any hint to solve this issue?

**Comment by mbw1210** [comment]
Hi, thats a common problem in Shopware with relative Image-Urls, not caused by this plugin

**Comment by JenSommer** [comment]
okay, thanx for the info - should the plugin be able to import via rest api the order details from the real.de marketplace? what is the right solution for an automated import of the orders from the marketplace? thanx for your help :)
